# Site settings
title: xianblue
url: "https://xianblue.github.io"
baseurl: ""
description: >
    블로그

# My information
email: sample@sample.mail
author: xianblue
profile:
twitter_username:
github_username: xianblue
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: xianblue
  shortname: xianblue
utterances:
  repo: xianblue/xianblue.github.io
  issue-term: pathname
  label: Comment
  branch: master

  # google_analytics:
  #   ua: UA-110224147-1

  # google_adsense:
  #   client: ca-pub-3675948545737694

blame: "https://github.com/xianblue/xianblue.github.io/blame/master/_wiki"
edit: "https://github.com/xianblue/xianblue.github.io/edit/master/_wiki"
issue: "https://github.com/xianblue/xianblue.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
